# Generated by Django 2.0.2 on 2020-02-16 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.IntegerField()),
                ('bookings', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookie', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=12)),
                ('bookingdate', models.DateField()),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('bookingmode', models.CharField(max_length=20)),
                ('bookingamount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('remainigamount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(max_length=20)),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementApp.Room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=30)),
                ('roomimg', models.ImageField(blank='True', upload_to='productImg')),
                ('totalrooms', models.IntegerField()),
                ('roomsize', models.IntegerField()),
                ('roomview', models.CharField(max_length=30)),
                ('roomoccupancy', models.IntegerField()),
                ('roomprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('roomdesc', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='roombooking',
            name='roomtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementApp.RoomType'),
        ),
        migrations.AddField(
            model_name='room',
            name='roomtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementApp.RoomType'),
        ),
    ]
