# Generated by Django 2.0.2 on 2020-02-16 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementApp', '0003_auto_20200216_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyFitnessPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('expdate', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(blank='True', upload_to='productImg')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cat', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(blank='True', upload_to='productImg')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(blank='True', upload_to='productImg')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cat', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('drinktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementApp.Drink')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('foodtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementApp.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Suscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='buyfitnesspack',
            name='drinktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementApp.FitnessPack'),
        ),
    ]
