# Generated by Django 2.0.2 on 2020-02-16 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementApp', '0004_auto_20200217_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyfitnesspack',
            old_name='drinktype',
            new_name='packtype',
        ),
    ]
