# Generated by Django 2.0.2 on 2020-02-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementApp', '0006_auto_20200217_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyfitnesspack',
            name='mob',
        ),
        migrations.RemoveField(
            model_name='orderdrink',
            name='mob',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='mob',
        ),
        migrations.AddField(
            model_name='buyfitnesspack',
            name='email',
            field=models.CharField(default='xyz@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdrink',
            name='email',
            field=models.CharField(default='xyz@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderfood',
            name='email',
            field=models.CharField(default='xyz@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
