# Generated by Django 2.0.2 on 2020-02-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementApp', '0007_auto_20200217_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdrink',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='email',
        ),
        migrations.AddField(
            model_name='orderdrink',
            name='roomno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdrink',
            name='tableno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderfood',
            name='roomno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderfood',
            name='tableno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
