# Generated by Django 2.0.2 on 2020-02-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementApp', '0008_auto_20200217_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdrink',
            name='tableno',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='tableno',
        ),
    ]
