# Generated by Django 2.0.2 on 2020-02-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementApp', '0009_auto_20200217_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdrink',
            name='roomno',
        ),
        migrations.RemoveField(
            model_name='orderfood',
            name='roomno',
        ),
        migrations.AddField(
            model_name='orderdrink',
            name='mob',
            field=models.CharField(default='7999702848', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderfood',
            name='mob',
            field=models.CharField(default='7999702848', max_length=10),
            preserve_default=False,
        ),
    ]
